# Generated by Django 6.0.2 on 2026-02-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sigil', models.CharField(blank=True, help_text='Description of the sigil', max_length=500)),
                ('words', models.CharField(blank=True, max_length=200)),
                ('seat', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('founded', models.CharField(blank=True, help_text='When was it founded?', max_length=100)),
                ('extinct', models.CharField(blank=True, help_text='If extinct, when?', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='houses/')),
            ],
            options={
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('also_known_as', models.JSONField(blank=True, default=list, help_text='Other names/titles')),
                ('born', models.CharField(blank=True, help_text="e.g., '283 AC' or 'In 273 AC at Dragonstone'", max_length=100)),
                ('died', models.CharField(blank=True, help_text="e.g., '298 AC' or 'During the Rebellion'", max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('culture', models.CharField(blank=True, max_length=100)),
                ('titles', models.JSONField(blank=True, default=list)),
                ('dragon', models.CharField(blank=True, help_text='Name of dragon if rider', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (from APIs)', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='characters/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_father', to='characters.character')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_mother', to='characters.character')),
                ('spouse', models.ManyToManyField(blank=True, to='characters.character')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='characters.house')),
            ],
        ),
    ]
