# Generated by Django 4.2 on 2026-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
