# Generated by Django 6.0.2 on 2026-02-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(choices=[('north', 'The North'), ('westerlands', 'The Westerlands'), ('reach', 'The Reach'), ('stormlands', 'The Stormlands'), ('dorne', 'Dorne'), ('vale', 'The Vale'), ('iron_islands', 'Iron Islands'), ('crownlands', 'Crownlands'), ('essos', 'Essos')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
