# Generated by Django 6.0.2 on 2026-02-17 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('houses', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('battle', 'Battle'), ('death', 'Death'), ('coronation', 'Coronation'), ('betrayal', 'Betrayal'), ('political', 'Political Event'), ('other', 'Other')], max_length=50)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('involved_characters', models.ManyToManyField(blank=True, related_name='events', to='characters.character')),
                ('involved_houses', models.ManyToManyField(blank=True, related_name='events', to='houses.house')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.location')),
            ],
        ),
    ]
